/**
 * PrefetchLink Component
 *
 * Wraps next/link with prefetch={true} for internal links generated by
 * InternalLinkingEngine. Ensures visible internal links are prefetched
 * for improved navigation performance.
 *
 * This is a Server Component — no "use client" directive.
 *
 * @see Requirements 1.16
 */

import Link from 'next/link';
import type { ComponentPropsWithoutRef } from 'react';

// ============================================================================
// Types
// ============================================================================

type PrefetchLinkProps = Omit<ComponentPropsWithoutRef<typeof Link>, 'prefetch'>;

// ============================================================================
// Component
// ============================================================================

/**
 * Internal link component with prefetch enabled.
 *
 * Use this for all internal links generated by InternalLinkingEngine
 * (related links, breadcrumb links) to enable automatic prefetching
 * when the link is visible in the viewport.
 */
export function PrefetchLink({ children, ...props }: PrefetchLinkProps) {
  return (
    <Link prefetch={true} {...props}>
      {children}
    </Link>
  );
}
